// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRZeyTZbMC1SPC22V-8Y23tU-HqGPt_Q',
    appId: '1:1076166063633:web:39b1abfed4ed75e5a863b0',
    messagingSenderId: '1076166063633',
    projectId: 'souq-gad',
    authDomain: 'souq-gad.firebaseapp.com',
    storageBucket: 'souq-gad.firebasestorage.app',
    measurementId: 'G-73XBZCTT9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgkfCf2SB6Lczpbx2kcz0aLs2Hb9cEhus',
    appId: '1:1076166063633:android:b0307c776f0ad0cea863b0',
    messagingSenderId: '1076166063633',
    projectId: 'souq-gad',
    storageBucket: 'souq-gad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM9UWHZUZ93uTWg8_ihlgS4DkoQ7i2T9k',
    appId: '1:1076166063633:ios:5e7a27d2cd159633a863b0',
    messagingSenderId: '1076166063633',
    projectId: 'souq-gad',
    storageBucket: 'souq-gad.firebasestorage.app',
    androidClientId: '1076166063633-af37b5tskqo8354ivho9addmrsl8jn9q.apps.googleusercontent.com',
    iosClientId: '1076166063633-4lsi1dvkdvlgjdrgbt14c9uomt0e2trb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM9UWHZUZ93uTWg8_ihlgS4DkoQ7i2T9k',
    appId: '1:1076166063633:ios:5e7a27d2cd159633a863b0',
    messagingSenderId: '1076166063633',
    projectId: 'souq-gad',
    storageBucket: 'souq-gad.firebasestorage.app',
    androidClientId: '1076166063633-af37b5tskqo8354ivho9addmrsl8jn9q.apps.googleusercontent.com',
    iosClientId: '1076166063633-4lsi1dvkdvlgjdrgbt14c9uomt0e2trb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruiteDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVRZeyTZbMC1SPC22V-8Y23tU-HqGPt_Q',
    appId: '1:1076166063633:web:40596abf02761363a863b0',
    messagingSenderId: '1076166063633',
    projectId: 'souq-gad',
    authDomain: 'souq-gad.firebaseapp.com',
    storageBucket: 'souq-gad.firebasestorage.app',
    measurementId: 'G-F798CBS8XE',
  );
}
